name = "pack_LBC"
author = "Fidrall"
version = "1.0.59"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57f102220a22156de2a38c91e74a27f75e13a047208c833ba8b157ff4efb2e7f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
