name = "pack_LBC"
author = "Fidrall"
version = "1.0.36"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a5d7ab299d53e35f23c1cacb728469c63d7109a058335e391e15ab8158ab5ae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
