name = "pack_LBC"
author = "Fidrall"
version = "1.0.22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7b8615a518a40b1e6c0294b7ad4de0b460e6e6c752915d335b6841d44e81a72"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
